version: "3"

services:
  test:
    build:
      context: .
      target: test
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 50M
    restart: on-failure
    volumes:
      - .:/var/www/html/app
      - contained_node_modules:/var/www/html/app/node_modules
    tty: true
    stdin_open: false
    command: npm run test:watch_unit

volumes:
  contained_node_modules:
